project_name: homestead

snapshot:
  name_template: "{{ .ShortCommit }}"

builds:
  - id: emquery
    main: ./cmd/emquery/main.go
    binary: emquery
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: weather-index-builder
    main: ./cmd/weather-index-builder/main.go
    binary: weather-index-builder
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: homestead
    name_template: "homestead_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'homestead_checksums.txt'
