apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "index-builder.fullname" . }}
  labels:
    {{- include "index-builder.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "index-builder.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumes:
            - name: config
              secret:
                secretName: {{ include "index-builder.fullname" . }}-config
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                - name: CONFIG_FILE
                  value: /opt/homestead/conf/config.json
                - name: INDEX_ENDPOINT
                  value: {{ .Values.endpoint }}
              command:
                - /opt/homestead/bin/{{ .Values.binary }}
              volumeMounts:
                - mountPath: /opt/homestead/conf
                  name: config
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
