apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "index-builder.fullname" . }}
  labels:
    {{- include "index-builder.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "index-builder.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumes:
            - name: config
              secret:
                secretName: {{ include "index-builder.fullname" . }}-config
            - name: index
              persistentVolumeClaim:
                claimName: {{ include "index-builder.fullname" . }}-index
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                - name: CONFIG_FILE
                  value: /opt/homestead/conf/config.json
                - name: INDEX_PATH
                  value: /opt/homestead/lib/bleve
                - name: INDEX_TARGET
                  value: "localhost:8080"
                - name: INDEX_TAGS
                  value: {{ .Values.tags | join "," | quote }}
              command:
                - /opt/homestead/bin/{{ .Values.binary }}
              volumeMounts:
                - mountPath: /opt/homestead/conf
                  name: config
                - mountPath: /opt/homestead/lib
                  name: index
            - name: aetherfs
              securityContext:
                {{- toYaml .Values.aetherfs.securityContext | nindent 16 }}
              image: "{{ .Values.aetherfs.image.repository }}:{{ .Values.aetherfs.image.tag }}"
              imagePullPolicy: {{ .Values.aetherfs.image.pullPolicy }}
              resources:
                {{- toYaml .Values.aetherfs.resources | nindent 16 }}
              env:
                - name: AGENT_ENABLE
                  value: "true"
                - name: AGENT_SHUTDOWN_ENABLE
                  value: "true"
                - name: STORAGE_DRIVER
                  value: none
              args:
                - run
              volumeMounts:
                - mountPath: /opt/homestead/lib
                  name: index
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
