apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "index-builder.fullname" . }}-index
  labels:
    {{- include "index-builder.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
