{
 "title": "Weather",
 "time": { "from": "now-6h", "to": "now+5d" },
 "panels": [
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__time(timestamp), avg(temperature) as temperature FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT $__time(timestamp), avg(apparent_temperature) as feels_like FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Rainfall (mm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__time(timestamp), avg(quantitative_precipitation) as rainfall FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Snow and Ice (mm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__time(timestamp), avg(snowfall_amount) as snow_fall FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT $__time(timestamp), avg(snow_level) as snow_accumulated FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT $__time(timestamp), avg(ice_accumulation) as ice_accumulated FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Wind Speed and Gusts (kph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__time(timestamp), avg(wind_speed) as speed FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    },
    {
     "rawSql": "SELECT $__time(timestamp), avg(wind_gust) as gust FROM weather WHERE $__timeFilter(timestamp) GROUP BY timestamp ORDER BY timestamp"
    }
   ]
  }
 ]
}